### ISSUE TITLE
question about the test dataset 

### ISSUE THREAD

**Issue by zfs1993** [sirius-ai/MobileFaceNet_TF#10]
the result on agedb_30 is not very good, especially the val result. it makes me confused. dose the val means the validate accuracy? it is really small.

**Comment by zfs1993** [comment]
thanks ,i got it. by the way,what is the validation rate of agedb in you experiment .mine result is really bad ,and i test the model i train,which accuracy on lfw is more 0.98,with some photo of mine，the result isn't very good. did you test the model with your pictures? 
i want to apply it to a mobile device. so i am concerned with the actual performance, i test the facenet,it works good. i just doubt the performance of the model in practical application。do you have any advice on it?

**Comment by sirius-ai** [comment]
Pretrained model had release yet, please test it by yourself.
