### ISSUE TITLE
what should i do if the train_batch_size has to be set to 64

### ISSUE THREAD

**Issue by SOLARleisu** [sirius-ai/MobileFaceNet_TF#11]

**Comment by sirius-ai** [comment]
you can try, I also had not tested like this.

**Comment by jetsmith** [comment]
@SOLARleisu my setting is same as your,  how is your training , have your succeed to train it now?

**Comment by sirius-ai** [comment]
train_batch_size is depend on your gpu total memory size.
close. when it necessary will reopen.
