### ISSUE TITLE
ValueError: A value in x_new is above the interpolation range.

### ISSUE THREAD

**Issue by aguang1201** [sirius-ai/MobileFaceNet_TF#13]
When training model the error happened.It look like some thing wrong in interpolate.interp1d(fpr, tpr) 
My scipy version is 1.1.0

**Comment by phoebushe** [comment]
i got the same problem..

**Comment by sirius-ai** [comment]
I can't reproduce that case, maybe you should use default parameters at first, and check your datasets.

**Comment by NinKjash** [comment]
> 我遇到了同样的问题..
我也遇到同样的问题，请问后来解决了吗

**Comment by NinKjash** [comment]
遇到同样的问题，请问有解决吗

**Comment by wangxinzhe0617** [comment]
@aguang1201 change line 263 as eer = brentq(lambda x: 1. - x - interpolate.interp1d(fpr, tpr, fill_value="extrapolate")(x), 0., 1.) can slove this problem.

**Comment by wangxinzhe0617** [comment]
@phoebushe change line 263 as eer = brentq(lambda x: 1. - x - interpolate.interp1d(fpr, tpr, fill_value="extrapolate")(x), 0., 1.) can slove this problem.

**Comment by phoebushe** [comment]
@wangxinzhe0617  thanks!

**Comment by sirius-ai** [comment]
@wangxinzhe0617 , thanks you.
close. when neccessary reopened.
