### ISSUE TITLE
training time info

### ISSUE THREAD

**Issue by cvtower** [sirius-ai/MobileFaceNet_TF#14]
Hi @sirius-ai ,

Nice work and the final performance!
Would you please share the training cost here? e.g. GPU detail, training hours.
Since i have only 1080ti and would like to estimate the training time before working, you know not everyone has the computation power as google.

Thanks very much!

**Comment by sirius-ai** [comment]
I use one nvidia p40 and training at default parameters that cost aboult 3days and 10 hours.

**Comment by cvtower** [comment]
@sirius-ai 

Got it! Thanks!
