### ISSUE TITLE
Error of pretrained model

### ISSUE THREAD

**Issue by larsonwu0220** [sirius-ai/MobileFaceNet_TF#20]
The error is AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path' when I run the train_nets.py using the pre-trained model MobileFaceNet_9925_9680.pb.
#193 ckpt = tf.train.get_checkpoint_state(pretrained_model) output ckpt = None.

The command in terminal is:
python train_nets.py --eval_db_path /<my directory>/faces_emore --tfrecords_file_path /<my directory>/tfrecords --pretrained_model /<my directory>/MobileFaceNet_9925_9680.pb

How can I solve it?
Thanks

**Comment by sirius-ai** [comment]
Because pretrained model isn‘t conclude loss variables，it just contain mobilefacenet variables, so you can try with low learning rate for training.

**Comment by sirius-ai** [comment]
close this issue, when need reopen.
