### ISSUE TITLE
How to change image size to 160x160

### ISSUE THREAD

**Issue by larsonwu0220** [sirius-ai/MobileFaceNet_TF#22]
want to training mobilefacenet with image size 160x160. I have modified mobilefacenet structure, but the data size is 112x112.
How to change size of dataset in Dataset Zoo?
Do you support resize function in the train script?
Thanks~

**Comment by sirius-ai** [comment]
firstly, redefine --image_size to [160, 160], then resize your training datasets to 160x160 in load_data(...) function, that will go fine.
close this issue, when need reopen,
