### ISSUE TITLE
verification problem

### ISSUE THREAD

**Issue by Joll123** [sirius-ai/MobileFaceNet_TF#25]
在lfw上验证准确度时为什么要embeddings=embeddings_list[0] + embeddings_list[1]。我用读图片的方式进行验证准确度并不高 ，谢谢  @sirius-ai

**Comment by yangqigege** [comment]
我也遇到这样的情况

**Comment by terryzhangthu** [comment]
同遇到这个问题，读取图片的方式进行验证准确度不高啊

**Comment by weiyuanqing** [comment]
> 同遇到这个问题，读取图片的方式进行验证准确度不高啊

你运行train_nets.py的时候出现memory error吗？我每次都是这样

**Comment by weiyuanqing** [comment]
> 我也遇到这样的情况
你运行train_nets.py的时候出现memory error吗？我每次都是这样

**Comment by weiyuanqing** [comment]
> 在lfw上验证准确度时为什么要embeddings=embeddings_list[0] + embeddings_list[1]。我用读图片的方式进行验证准确度并不高 ，谢谢 @sirius-ai

你运行train_nets.py的时候出现memory error吗？我不知道为什么。内存给了6g内存，训练的数据是2g的

**Comment by sirius-ai** [comment]
1、embeddings=embeddings_list[0] + embeddings_list[1]只是搬用了InsightFace_TF的代码，实际上并没有使用，推测是为了合并embeddings.
2、直接读图片的方式验证准确度不高，最有可能的原因是人脸截取的方式不一样，我的训练代码人脸的margin是40左右；
3、memory error，可能的原有是GPU内存被占用了，可运行nvidia-smi查看并kill掉相应的线程，另外就是调低batch size.

**Comment by Joll123** [comment]
@sirius-ai 你的人脸检测方法是什么  我把margin调到40准确率也很低

**Comment by NicoleNicoleXiang** [comment]
@Joll123 
您好，请问您解决了自己直接读取图片然后用mtcnn检测后验证准确率不高的情况了吗?

**Comment by NicoleNicoleXiang** [comment]
@sirius-ai ,作者，您好
请问您的图片是怎样进行预处理的？因为我想用自己的库来做人脸识别的硬件应用。
我现在是先用facente里面的mtcnn对lfw的数据集进行检测，并把图片剪裁为112*112，然后直接用PIL的Image直接读入lfw的图片。只测了10对人脸（5对一样，5对不一样），在用你的处理好的数据集验证率在90%左右，而在我自己处理的数据集上只有53%左右？

**Comment by AaronFan1992** [comment]
@NicoleNicoleXiang 可以参考下我基于 @sirius-ai 的模型开发的Demo，里面有预处理部分和验证部分的逻辑，可以直接读取图片或者视频流进行识别，地址：https://github.com/AaronFan1992/jetson_nano_demo/tree/master/face_recognition
