### ISSUE TITLE
doubt about application effects

### ISSUE THREAD

**Issue by zfs1993** [sirius-ai/MobileFaceNet_TF#28]
i trained the model for a long time .i reach the performance of the author.but when i use it for  comparison between the people and Certificates，it perform poorly and facenet has a much better result. do you have any advice or should i try another model?

**Comment by 714333462** [comment]
i have the same problem , do you find the reason?

**Comment by sirius-ai** [comment]
firstly, check face detect way is same or not，such as bbox、margin;
secondly, check image channel oder, confirm its format is RGB or BGR;
thirdly, input image pixel must subtract 127.5 then Multiplied by the 0.0078125.

**Comment by NicoleNicoleXiang** [comment]
hi， @sirius-ai 
what are your way of detect,like bbox,margin？
did you use the code of mtcnn in facenet library?

**Comment by deepak-neva** [comment]
It would be great if @sirius-ai could share how the detection actually is implemented. I am simply unable to make the mobilefacenet model work.

**Comment by sirius-ai** [comment]
I use mtcnn to detect faces，and margin is set to 44. If you can't make the model work, please follow the test_nets.py.
