### ISSUE TITLE
the loss keeping nan, and the accuracy is 0.0

### ISSUE THREAD

**Issue by CPH19960624** [sirius-ai/MobileFaceNet_TF#30]
![1548038473 1](https://user-images.githubusercontent.com/45925974/51449889-1c97e900-1d69-11e9-996d-27d29eb94acf.jpg)

i use u code and what should i change

**Comment by rimio** [comment]
See https://github.com/sirius-ai/MobileFaceNet_TF/issues/24

**Comment by sirius-ai** [comment]
had fix.
[here](https://github.com/sirius-ai/MobileFaceNet_TF/commit/47a9855ef861407ae75fa171597e7636ae9a9285)
