### ISSUE TITLE
how to create bin dataset file

### ISSUE THREAD

**Issue by longchr123** [sirius-ai/MobileFaceNet_TF#31]
this is load dataset code:
bins, issame_list = pickle.load(open(os.path.join(args.eval_db_path, db_name + '.bin'), 'rb'), encoding='bytes')

but how to create the bin file, like lfw.bin in https://github.com/deepinsight/insightface/wiki/Model-Zoo

**Comment by smartwell** [comment]
https://github.com/deepinsight/insightface/wiki/Dataset-Zoo

**Comment by sirius-ai** [comment]
pickle bin is a tuple(images, issame_list), and the element of tuple all are a list, so you should follow that to dump datas to pickle bin.
