### ISSUE TITLE
MobileFaceNet Struct 

### ISSUE THREAD

**Issue by zhanglaplace** [sirius-ai/MobileFaceNet_TF#32]
thanks for your good repo. maybe there has some miswake in network define
1、
in https://github.com/sirius-ai/MobileFaceNet_TF/blob/master/nets/MobileFaceNet.py#L52-L63
should be 
```python
_CONV_DEFS = [
    Conv(kernel=[3, 3], stride=2, depth=64, ratio=1),
    DepthwiseConv(kernel=[3, 3], stride=1, depth=64, ratio=1),
    InvResBlock(kernel=[3, 3], stride=2, depth=64, ratio=2, repeate=1), （first stride set to 2）
    InvResBlock(kernel=[3, 3], stride=1, depth=64, ratio=2, repeate=4),   （set stride to 1)
    InvResBlock(kernel=[3, 3], stride=2, depth=128, ratio=4, repeate=1),
    InvResBlock(kernel=[3, 3], stride=1, depth=128, ratio=2, repeate=6),
    InvResBlock(kernel=[3, 3], stride=2, depth=128, ratio=4, repeate=1),
    InvResBlock(kernel=[3, 3], stride=1, depth=128, ratio=2, repeate=2),
    Conv(kernel=[1, 1], stride=1, depth=512, ratio=1),
]
```
2、 first depthwise conv maybe not conv_em  in https://github.com/sirius-ai/MobileFaceNet_TF/blob/master/nets/MobileFaceNet.py#L138

**Comment by jackchinor** [comment]
hi, have you tried the modified structrure?  How is the performance? Thanks

**Comment by sirius-ai** [comment]
1. 
InvResBlock(kernel=[3, 3], stride=2, depth=64, ratio=2, repeate=1), （first stride set to 2）
InvResBlock(kernel=[3, 3], stride=1, depth=64, ratio=2, repeate=4),   （set stride to 1)

What's the difference? In my code, repeate is set to 5, but you divide it to 1 and 4, why?
I am follow the paper [MobileFaceNets: Efficient CNNs for Accurate RealTime Face Verification on Mobile Devices](https://arxiv.org/pdf/1804.07573.pdf), maybe there some misunderstand.

2.
depthwise is construct by slim.separable_conv2d and slim.conv2d.
