### ISSUE TITLE
can u provide your training ckpt model files 

### ISSUE THREAD

**Issue by vgg4resnet** [sirius-ai/MobileFaceNet_TF#33]
hi，can you provide your training ckpt model files， I am having problems to deploy your model on mobile devices

**Comment by sirius-ai** [comment]
pb file can convert to ckpt, you can try it use my train code follow that:
1. load pretrained model;
2. save to checkpoint files.

**Comment by freenlp** [comment]
@sirius-ai Can you share your trained ckpt model files? I want to filnetine. Can't convert pb to ckpt format.

**Comment by sirius-ai** [comment]
[released](https://github.com/sirius-ai/MobileFaceNet_TF/commit/26021f6fb435f3d6082b55f94a0774bcf49bc65a)
