### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by weiyuanqing** [sirius-ai/MobileFaceNet_TF#34]
hi，I have some problems,dont know why.Can you tell me?THX.

Use the retry module or similar alternatives.
begin db lfw convert.
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
loading bin 12000
(12000, 112, 112, 3)
begin db cfp_ff convert.
Traceback (most recent call last):
  File "train_nets.py", line 107, in <module>
    data_set = load_data(db, args.image_size, args)
  File "/home/ubuntu/wyq/MobileFaceNet_TF/utils/data_process.py", line 111, in load_data
    datasets = np.empty((len(issame_list)*2, image_size[0], image_size[1], 3))
MemoryError

**Comment by sirius-ai** [comment]
your computer memory is too tiny, so you can modify --eval_datasets to ['lfw'] and modify --train_batch_size to smaller.
