### ISSUE TITLE
Feature embeddigs - Euclidean Space

### ISSUE THREAD

**Issue by prnvjb** [sirius-ai/MobileFaceNet_TF#36]
Hi,
I'm doing 1:1 face verification. I tried to use this model but getting different cosine distances for face_pairs. I'm really confused.
Does the embeddings that are calculated by mobilefacenet are in the Euclidean space where distances
directly correspond to a measure of face similarity?
If not, how to calculate the similarity between two faces? As, I'm not planning to uses any clustering algorithm.

**Comment by sirius-ai** [comment]
same as [#35](https://github.com/sirius-ai/MobileFaceNet_TF/issues/35)
isn't cosine distance, it is euclidean, but without np.sqrt, see:
if pca == 0:
    diff = np.subtract(embeddings1, embeddings2)
    dist = np.sum(np.square(diff), 1)

**Comment by prnvjb** [comment]
Thanks @sirius-ai .
Worked!!

**Comment by dear-john** [comment]
@prnvjb  
 do you have try any clustering algorithm? I want to try this model to cluster album in mobile devices.

**Comment by prnvjb** [comment]
DBSCAN works or build yours' based on the distance parameter

**Comment by DietDietDiet** [comment]
@prnvjb Could u share how u found the threshold for the euclidean distance?  I found the distances are hardly separable whether the tested images are of same or different person.

**Comment by AaronFan1992** [comment]
I create a repository for face recognition demo using MTCNN and MobileFaceNet. It's maybe helping someone.
Please visit::
https://github.com/AaronFan1992/jetson_nano_demo/tree/master/face_recognition

**Comment by milinddeore** [comment]
@sirius-ai Apologies for commenting on a closed issue, but i think the question is related. 

We can also train SVM classifier to find same OR different person, just like classifier.py file in David'd FaceNet implementation. Do you think having just one embedding of person to compare VS multiple embeddings, for verification?
