### ISSUE TITLE
issue when run "test_nets.py"

### ISSUE THREAD

**Issue by barrycb** [sirius-ai/MobileFaceNet_TF#37]
When running 'test_nets.py' with pretrained model "MobileFaceNet_9925_9680.pb", met below issue，

MobileFaceNet_TF$ python test_nets.py --model=./arch/pretrained_model/MobileFaceNet_9925_9680.pb
begin db lfw convert.
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
loading bin 12000
(12000, 112, 112, 3)
Model filename: ./arch/pretrained_model/MobileFaceNet_9925_9680.pb
Runnning forward pass on lfw images

Traceback (most recent call last):
  File "test_nets.py", line 143, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "test_nets.py", line 104, in main
    emb_array = np.zeros((data_sets.shape[0], embedding_size))
TypeError: __index__ returned non-int (type NoneType)

MobileFaceNet_TF$ python --version
Python 3.4.3

BTW, test_nets.py can work well with default output/ckpt checkpoint files.
MobileFaceNet_TF$ python test_nets.py
begin db lfw convert.
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
loading bin 12000
(12000, 112, 112, 3)
Model directory: ./output/ckpt
Metagraph file: MobileFaceNet_pretrain.ckpt.meta
Checkpoint file: MobileFaceNet_pretrain.ckpt
Runnning forward pass on lfw images

thresholds max: 1.47 <=> min: 1.41
total time 974.123s to evaluate 12000 images of lfw
Accuracy: 0.993+-0.005
Validation rate: 0.98800+-0.00933 @ FAR=0.00100
fpr and tpr: 0.502 0.838
Area Under Curve (AUC): 0.999
Equal Error Rate (EER): 0.007

please help look at the issue, thank you.

**Comment by sirius-ai** [comment]
can you print data_sets.shape and embedding_size? if embedding_size is None, then you can set it to a fixed value such as 128 according to the embedding_size of train_nets.py.

**Comment by barrycb** [comment]
# Get input and output tensors, ignore phase_train_placeholder for it have default value.
inputs_placeholder = tf.get_default_graph().get_tensor_by_name("input:0")
print(inputs_placeholder)
embeddings = tf.get_default_graph().get_tensor_by_name("embeddings:0")
print(embeddings)

print log:
Tensor("input:0", shape=(?, 112, 112, 3), dtype=float32)
Tensor("embeddings:0", dtype=float32)

print(nrof_batches)
print(embedding_size), log as,
120
?

Tried embedding_size=128, it can get result about 99.2% with provided pretrained model, but I can't find the reason for this issue.

One more question was about waht parameters should be give to 'train_nets.py', we can only get about 50% accuracy print log while model training.
Run train model like this, "python3 train_nets.py"

Thank you.

**Comment by barrycb** [comment]
Add model training log,

run like this,
#python3 train_nets.py  --class_number 85164

datasets download from "Refined-MS1M@BaiduDrive"

running log,
epoch 0, total_step 61800, total loss is 46.94 , inference loss is 46.92, reg_loss is 0.02, training accuracy is 0.000000, time 79.425 samples/sec
epoch 0, total_step 61850, total loss is 45.62 , inference loss is 45.60, reg_loss is 0.02, training accuracy is 0.000000, time 78.992 samples/sec
epoch 0, total_step 61900, total loss is 43.58 , inference loss is 43.56, reg_loss is 0.02, training accuracy is 0.000000, time 79.505 samples/sec
epoch 0, total_step 61950, total loss is 44.49 , inference loss is 44.47, reg_loss is 0.02, training accuracy is 0.000000, time 79.909 samples/sec
epoch 0, total_step 62000, total loss is 47.39 , inference loss is 47.37, reg_loss is 0.02, training accuracy is 0.000000, time 79.712 samples/sec

Iteration 62000 testing...
thresholds max: 3.96 <=> min: 0.0
total time 748.597s to evaluate 12000 images of lfw
Accuracy: 0.500+-0.000
Validation rate: 0.57367+-0.03035 @ FAR=0.52833
fpr and tpr: 0.997 0.997
Area Under Curve (AUC): 0.499
Equal Error Rate (EER): 0.501

We want to train a workable pretrained model like "arch/pretrained_model/MobileFaceNet_9925_9680.pb"

thank you.

**Comment by sirius-ai** [comment]
args.class_number must be equal to your exactly datasets class number, and you should train more epoch.

**Comment by CHANGErIBE** [comment]
Hi I have faced the same problem.
When running 'test_nets.py' with pretrained model "MobileFaceNet_9925_9680.pb", met below issue，

MobileFaceNet_TF$ python test_nets.py --model=./arch/pretrained_model/MobileFaceNet_9925_9680.pb
begin db lfw convert.
loading bin 1000
loading bin 2000
loading bin 3000
loading bin 4000
loading bin 5000
loading bin 6000
loading bin 7000
loading bin 8000
loading bin 9000
loading bin 10000
loading bin 11000
loading bin 12000
(12000, 112, 112, 3)
Model filename: ./arch/pretrained_model/MobileFaceNet_9925_9680.pb
Runnning forward pass on lfw images

Traceback (most recent call last):
File "test_nets.py", line 143, in 
main(parse_arguments(sys.argv[1:]))
File "test_nets.py", line 104, in main
emb_array = np.zeros((data_sets.shape[0], embedding_size))
TypeError: index returned non-int (type NoneType)

then I set 128 or 512, the forward process was crashed as fallows:

2019-04-08 13:05:36.218402: E C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\executor.cc:644] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: MobileFaceNet/MobileFaceNet/Conv2d_0/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](_arg_input_0_0/_211, MobileFaceNet/Conv2d_0/weights/read). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
         [[Node: MobileFaceNet/MobileFaceNet/Conv2d_0/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](_arg_input_0_0/_211, MobileFaceNet/Conv2d_0/weights/read)]]
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1306, in _run_fn
    status, run_metadata)
  File "D:\Anaconda3\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: MobileFaceNet/MobileFaceNet/Conv2d_0/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](_arg_input_0_0/_211, MobileFaceNet/Conv2d_0/weights/read). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
         [[Node: MobileFaceNet/MobileFaceNet/Conv2d_0/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](_arg_input_0_0/_211, MobileFaceNet/Conv2d_0/weights/read)]]

so I think there is some wrong with pb file, can you solve this problem?

thank you

**Comment by CHANGErIBE** [comment]
with tf.Session() as sess:
                for op in tf.get_default_graph().get_operations():
                    a=sess.graph.get_tensor_by_name(op.name+":0")
                    print(op.name)
                    print(a.get_shape())
result follows:
img_inputs
(?, 112, 112, 3)
Const
()
phase_train
<unknown>
input
(?, 112, 112, 3)
...
...
MobileFaceNet/Logits/SpatialSqueeze
<unknown>
embeddings/Square
<unknown>
embeddings/Sum/reduction_indices
()
embeddings/Sum
<unknown>
embeddings/Maximum/y
()
embeddings/Maximum
<unknown>
embeddings/Rsqrt
<unknown>
embeddings
<unknown>

embeddings.shape unknown,can you solve this problem?

thank you

**Comment by CHANGErIBE** [comment]
with tf.Session() as sess:
                for op in tf.get_default_graph().get_operations():
                    a=sess.graph.get_tensor_by_name(op.name+":0")
                    print(op.name)
                    print(a.get_shape())

result follows:
img_inputs
(?, 112, 112, 3)
Const
()
phase_train
unknown
input
(?, 112, 112, 3)

...

MobileFaceNet/Logits/SpatialSqueeze
unknown
embeddings/Square
unknown
embeddings/Sum/reduction_indices
()
embeddings/Sum
unknown
embeddings/Maximum/y
()
embeddings/Maximum
unknown
embeddings/Rsqrt
unknown
embeddings
unknown

the embeddings.shape is unknown,can you solve this problem?

thank you

**Comment by sirius-ai** [comment]
[use ckpt model](https://github.com/sirius-ai/MobileFaceNet_TF/commit/26021f6fb435f3d6082b55f94a0774bcf49bc65a)
