### ISSUE TITLE
about arcface_loss

### ISSUE THREAD

**Issue by TiramisuJ** [sirius-ai/MobileFaceNet_TF#4]
Nice work! but you use cos_loss instead of arcface_loss.When i use the arcface_loss, the loss will be nan,and the accuracy will drop.Have you ever been in the same situation

**Comment by xsr-ai** [comment]
since the cosine loss and arcface loss are similar, and in my experiment, the first reach better acc, so use the cosine loss advance. for your case, maybe you should modify the hyperparametes, and later when i have time i will update the source code.

**Comment by sirius-ai** [comment]
close, when need reopen.
