### ISSUE TITLE
Adapt for 224x224 input

### ISSUE THREAD

**Issue by batrlatom** [sirius-ai/MobileFaceNet_TF#42]
How can I adapt your MobileFaceNet model to process standart Mobilenet image size? 
You have defined a variable mobilenet_v2.default_image_size = 112, but it is not used anywhere I think. Thanks

**Comment by sirius-ai** [comment]
you should prepare your training datasets and refine the image size, than trainning by yourself.
mobilenet_v2.default_image_size is not use anywhere, it just tell the default image size of input.
