### ISSUE TITLE
1:1 face matching

### ISSUE THREAD

**Issue by dear-john** [sirius-ai/MobileFaceNet_TF#43]
What is the threshold if i want to do 1:1 face matching in mobile phone with .pb model ?

i had tried set threshold to 1.234 ,but it seem do not work well.

**Comment by DietDietDiet** [comment]
你好，请问你找到合适的threshold了嘛？可否加个微信交流下

**Comment by dear-john** [comment]
现在还没找到，我也很困惑

**Comment by DietDietDiet** [comment]
> 现在还没找到，我也很困惑

你是用的自己的数据集评估的吗。我在自己的数据集上性能下降的很厉害

**Comment by sirius-ai** [comment]
不同的阈值会得到不同的误识率和拒识率，请使用自有的测试集画出ROC并确认合适的阈值。

**Comment by dear-john** [comment]
我没有自己的数据集，我用的就是repo提供的pb文件，然后部署在手机上进行识别。
我开始设置的阈值1.234是用的LFW的最佳阈值取平均得到的，但实际效果不好。

**Comment by sirius-ai** [comment]
lfw是外国人脸的数据集，而你要应用的测试人脸应该是国内的，建议阈值设定在0.8~1.0之间，然后自己进行测试调整。

**Comment by dear-john** [comment]
好的，谢谢，我会尝试一下的
