### ISSUE TITLE
how to test and evaluate it ?

### ISSUE THREAD

**Issue by mengfu188** [sirius-ai/MobileFaceNet_TF#44]
How to get the tpr, fpr, accuracy, val, val_std, far indicator results.
In the test_nets.py,I found code under. however the parameter of `issame_list` is the list of boolean, I don' t understand that?
```py
tpr, fpr, accuracy, val, val_std, far = evaluate(emb_array, issame_list, nrof_folds=args.eval_nrof_folds)```

**Comment by sirius-ai** [comment]
please see the function evaluate source code：
embeddings1 = embeddings[0::2]
embeddings2 = embeddings[1::2]
issame_list reveal embeddings1 and embeddings2 is same people embeddings or not, True is same, otherwise is difference.

**Comment by mengfu188** [comment]
Is this the usual way to test?
I am a rookie.

**Comment by sirius-ai** [comment]
yes, tpr, fpr, accuracy, val, val_std, far there calculation method is same.

**Comment by mengfu188** [comment]
Thank you very mach.

**Comment by chaitanyakkumar** [comment]
Can anybody please explain, what val and val_std mean?
