### ISSUE TITLE
inference loss

### ISSUE THREAD

**Issue by DietDietDiet** [sirius-ai/MobileFaceNet_TF#45]
想请问下作者训练的inference loss大概收敛到多少，我的loss最终总是在8-10左右

**Comment by sirius-ai** [comment]
能贴一下模型在各个测试集的指标吗？

**Comment by DietDietDiet** [comment]
@sirius-ai  基于MS1M-v2训练的模型
lfw accuracy 99.3 val rate@far1e-3 98.26 
agedb_30 accuracy 0.941 val rate@far1e-3 65.33

**Comment by zfs1993** [comment]
> 想请问下作者训练的inference loss大概收敛到多少，我的loss最终总是在8-10左右

我也差不多loss到这个数，然后acc有0.2的样子，但是这结果完全不行呀

**Comment by siyiding1216** [comment]
> > 想请问下作者训练的inference loss大概收敛到多少，我的loss最终总是在8-10左右
> 
> 我也差不多loss到这个数，然后acc有0.2的样子，但是这结果完全不行呀

Same here. Did you manage to get around 0.5 accuracy as the author did?

**Comment by dangnh0611** [comment]
@zfs1993  @siyiding1216  Same here. Did the problem fixed?
