### ISSUE TITLE
Training classification accuracy?

### ISSUE THREAD

**Issue by capilano** [sirius-ai/MobileFaceNet_TF#51]
What is your classification accuracy (approximate value) towards the end of training? and what is the general range to be expected for classification scores? 
I am using a variant of mobilenet and my classification accuracy is abut 0.54 with around 90K classes(unique faces).

**Comment by sirius-ai** [comment]
acc ：99.4%+，trainning sets：MS1M-V2

**Comment by capilano** [comment]
@sirius-ai ai. On LFW?1-1verification? Yes,thats what I get as well appx 99.45.
 I meant classification accuracy on training set. (How many examples are classified correctly? I doubt that it will be more than 60 percent since there are about 85K classes

**Comment by sirius-ai** [comment]
on trainingsets acc reach approximately 50%.

**Comment by capilano** [comment]
@sirius-ai Thanks. What data augmentations did you use apart from  random flip and rotate?  Any color augmentations? 
Also, for the evaluation, did you get same result using Euclidean distance and PCA?

**Comment by sirius-ai** [comment]
1) I use default datasets of MS1M-V2, not contrain any data augmentations.
2) difference.
