### ISSUE TITLE
it seems the pb file is only graph info

### ISSUE THREAD

**Issue by QuarK30** [sirius-ai/MobileFaceNet_TF#52]
when I convert the pb file to ckpt, it raise the ValueError ("No variables to save"), so is this any solution.

**Comment by sirius-ai** [comment]
convert pb file to ckpt format is a hard work, I will release ckpt file later.

**Comment by sirius-ai** [comment]
[ckpt files had released](https://github.com/sirius-ai/MobileFaceNet_TF/commit/26021f6fb435f3d6082b55f94a0774bcf49bc65a)
