### ISSUE TITLE
损失函数的值从10000轮左右开始就在20左右晃一直不下降了

### ISSUE THREAD

**Issue by flyduck** [sirius-ai/MobileFaceNet_TF#54]
您好，
首先非常感谢您公开的代码，我在使用该代码进行训练网络的时候，使用了celeba数据集，训练数据集大概有15万左右，类别是8000多，刚开始的时候损失函数下降的很快，到10000轮迭代的时候就出现在20左右一直晃，一直到20万轮迭代还是在20左右晃，请问您知道这是为什么吗？我修改了一些超参数还是不能改变这个状况～
谢谢！

**Comment by sirius-ai** [comment]
需要清洗一下数据，可以使用[Chinese wishper](https://github.com/zhly0/facenet-face-cluster-chinese-whispers-)进行数据清洗，超参调整可以考虑降低lr、insight face loss中的s和m、加大batch size以及使用不同的优化器。

**Comment by flyduck** [comment]
谢谢您的回复，您使用过celeba这个数据集训练吗？大概是20万的数据，作为训练集的话是不是不够用啊？
另外，您在使用MS-Celeb-1M的数据训练的时候是直接使用insightface里面给出的align后的数据吗？请问您有没有该数据集的原始数据呀？可不可以分享一下呢，因为我需要自己做对齐再训练。

非常感谢您的回复

**Comment by flyduck** [comment]
还有一个问题，就是关于atchsize，您是使用的512吗？我现在只能使用64的batchsize，加大batchsize的话GPU就溢出了，请问您使用的是什么GPU啊？非常感谢

**Comment by sirius-ai** [comment]
1）CelebA这个数据集是有点小了；
2）我是直接使用insightface里面给出的align好的数据集的，如果要更好的效果，那就做数据增强和均衡，原始的MS1M数据集好像官方不开放下载了；
3）batchsize根据自身硬件资源调整了，我自用的GPU有1080ti和1060ti两种；

**Comment by flyduck** [comment]
谢谢您的耐心解答，我现在使用ms1m的300多万那个数据集在训练了，但是当总损失函数降到8左右就基本上维持在这个水平了，训练数据的accuracy是0.3左右，不知道您当时训练的时候最好的结果是到什么值呢？
另外，仔细阅读代码后，在arface_loss这个函数中，其中有写到thita+m需要限定在0到pi的范围内，请问这个是由于需要限制cos函数的单调性吗？
如果我上述问题成立，其中不满足条件的时候需要使用keep_val这个值，为什么keep_val的值计算方式是s*(cos_t-m*sin_m)呢？
非常感谢！

**Comment by sirius-ai** [comment]
1、thita+m需要限定在0到pi的范围内我理解也是为了限制cos在周期内的单调性；
2、cos_mt就是真正的归一化后的特征向量和特定权重的s*cos(t+m)的值，而keep_val为s*(cos(t) - sin(m) *m)，针对你这个问题，我的理解是要从cos_mt_temp上来反推，他在求logit时是求的同一类ID的logit，那么应该希望他是正数且最大的，因为两个向量同向时其余弦值最大，而cond这个限定了当两个向量的夹角大于pi-m小于pi时其余弦值为负值，那么经过tf.cast和tf.where处理后就是要选择keep_value，此时cos(t)是为负数接近为-1的，而sin(m) *m无论如何在0到pi内都大于0，这样keep_value的值就一定会是负数且是最小的负数，此时，loss损失值最大，梯度最大，模型可继续学习的更多。

**Comment by flyduck** [comment]
谢谢您的解答，请问您试过使用单机多GPU来训练过这个分类模型吗？我在使用单机多GPU训练的时候出现训了几轮之后有一个GPU的显存会明显增加，但是我使用同样的代码来训练类别数较少的分类任务时不会出现这个问题，请问您知道这是为什么吗？谢谢

**Comment by flyduck** [comment]
啊，对了，我还发现个问题啊，那个论文中写的网络结构那个表格，其中t应该是该个block重复的次数吧？和你这个代码似乎不能对应呢？

**Comment by wongzzzy** [comment]
> 需要清洗一下数据，可以使用[Chinese wishper](https://github.com/zhly0/facenet-face-cluster-chinese-whispers-)进行数据清洗，超参调整可以考虑降低lr、insight face loss中的s和m、加大batch size以及使用不同的优化器。

您好，我也存在loss保持20左右的问题，数据清洗是暂停训练后的模型进行的吗，我看Chinese wishper中需要输入模型，我不清楚这个需要输入的模型是什么

**Comment by sirius-ai** [comment]
@flyduck 这个显存明显增加的GPU是不是也突然负担了其他任务？另外，你检查一下你的代码是否存在不断在迭代循环内添加了Ops的动作了？或者在迭代循环内有不断扩展显存使用的操作？你可以交换不同的GPU看是否某段特定的任务才会造成这个问题！

**Comment by sirius-ai** [comment]
@wongzzzy 这个输入模型一般是精确度很高的模型哦，别如使用insightface的最好模型，这样清洗出来的数据才够干净，不过越大的模型会增加清洗耗时。

**Comment by wongzzzy** [comment]
> @wongzzzy 这个输入模型一般是精确度很高的模型哦，别如使用insightface的最好模型，这样清洗出来的数据才够干净，不过越大的模型会增加清洗耗时。

多谢！

**Comment by flyduck** [comment]
> @flyduck 这个显存明显增加的GPU是不是也突然负担了其他任务？另外，你检查一下你的代码是否存在不断在迭代循环内添加了Ops的动作了？或者在迭代循环内有不断扩展显存使用的操作？你可以交换不同的GPU看是否某段特定的任务才会造成这个问题！

谢谢您的回答，我调换了GPU的顺序还是会出现这个问题，我使用基础模型是完整的mobilenetv2来做的，后来我把输入图像从224改成112然后使用每个GPU的batchsize为128就不会总是出现一个GPU突然负荷增加的情况了，可以训练成功，但是偶尔的可能会出现某个GPU突然增加负荷的情况，机器没有运行其他的任务，不知道为什么，要是出现这个情况了就重新启动训练有可能就能成功训练，有一定的偶然性。您说的那个内部循环添加ops这个问题该怎么查呀？

**Comment by sirius-ai** [comment]
@flyduck 找出问题所在了吗？问题解决了吧?

**Comment by zfs1993** [comment]
> 谢谢您的耐心解答，我现在使用ms1m的300多万那个数据集在训练了，但是当总损失函数降到8左右就基本上维持在这个水平了，训练数据的accuracy是0.3左右，不知道您当时训练的时候最好的结果是到什么值呢？
> 另外，仔细阅读代码后，在arface_loss这个函数中，其中有写到thita+m需要限定在0到pi的范围内，请问这个是由于需要限制cos函数的单调性吗？
> 如果我上述问题成立，其中不满足条件的时候需要使用keep_val这个值，为什么keep_val的值计算方式是s*(cos_t-m*sin_m)呢？
> 非常感谢！

我用亚洲数据集训练了一下，发现训练结果和你差不多，loss大约也是降到了8左右，acc不到0.3，不管怎么调节lr都无法获得更高的结果了，头疼,请问你后面有什么解决办法嘛？

**Comment by flyduck** [comment]
> @flyduck 找出问题所在了吗？问题解决了吧?

@sirius-ai 问题解决了，我自己新改的模型在损失函数计算的时候，输入参数搞错了，导致训练的时候出现了类似于梯度爆炸的问题，改完就好了，但是多个GPU训练的时候还是会出现有一个GPU占用空间比另外两个GPU大的情况，我相或许是有一些多个GPU的梯度融合计算等操作在这个GPU上计算吧。但是训练正常了，训练结果也和作者给出的测试结果差不多。非常感谢您！

**Comment by flyduck** [comment]
> > 谢谢您的耐心解答，我现在使用ms1m的300多万那个数据集在训练了，但是当总损失函数降到8左右就基本上维持在这个水平了，训练数据的accuracy是0.3左右，不知道您当时训练的时候最好的结果是到什么值呢？
> > 另外，仔细阅读代码后，在arface_loss这个函数中，其中有写到thita+m需要限定在0到pi的范围内，请问这个是由于需要限制cos函数的单调性吗？
> > 如果我上述问题成立，其中不满足条件的时候需要使用keep_val这个值，为什么keep_val的值计算方式是s*(cos_t-m*sin_m)呢？
> > 非常感谢！
> 
> 我用亚洲数据集训练了一下，发现训练结果和你差不多，loss大约也是降到了8左右，acc不到0.3，不管怎么调节lr都无法获得更高的结果了，头疼,请问你后面有什么解决办法嘛？

@zfs1993 我后来训练的结果是损失函数在不到3的样子的，用的是微软那个别人做完对齐处理的数据集，ID数是比较大的，你看看是不是你那个数据集ID数有点少，如果从头训练这个模型ID数少的话就可能训不好，你考以考虑拿大的数据集训练后再拿你的数据做微调的。

**Comment by shuaijun-deng** [comment]
@flyduck 我也遇到和你类似的情况，使用的是处理亚洲人脸那个数据集，我把类别中小于50以下的照片筛选了出去，最后数据集有8559个ID,200多万张图片。但是损失函数下降到20左右就不下降了，使用的作者给出的训练好的模型进行微调的还是这样。
![image](https://user-images.githubusercontent.com/63647047/83985084-5ec7c780-a96a-11ea-97e7-94efb6bdc55d.png)请问您是怎么解决的

**Comment by flyduck** [comment]
@shuaijun-deng 你训练的batchsize是多少？如果batchsize太小可能也会出这样的问题吧，原始模型有好久没训了，现在都改得面目全非的，有些细节想不起来了～～实在不好意思

**Comment by Casi11as** [comment]
我是用casia训练的有，原始数据集有10575类，也是loss在20就不下降了。然后我听从建议用chinese whisper清洗，但是不是很明白这个过程，现在是每一个人（类）文件夹下面又多了几个子文件夹，每个子文件夹里是最相似的几张人脸图片，那么我怎么用清洗好的这些数据继续训练呢？需要改类别数量吗？
