### ISSUE TITLE
如何比对两张图片是否是一个人

### ISSUE THREAD

**Issue by syaringan357** [sirius-ai/MobileFaceNet_TF#56]

**Comment by HandsLing** [comment]
对这两张图片的特征计算欧氏距离，设定一个阈值，小于这个阈值就是同一个人，反之则不是同一个人

**Comment by Ozone-oo** [comment]
@HandsLing 
您好，我想问下这个模型是用欧式距离来比较的嘛？您有测试过吗？

**Comment by Ozone-oo** [comment]
@syaringan357 
您好，请问您的问题解决了吗？我也遇到了这个问题

**Comment by HandsLing** [comment]
@YunShaw95 是的，我是用欧氏距离来比较的。但是不同的数据可能对不同的阈值敏感，需要去测试得到最合适的阈值才行

**Comment by Ozone-oo** [comment]
@HandsLing 好的，了解了，我去试下，非常感谢您的回复

**Comment by sirius-ai** [comment]
欧式距离或余弦距离都可以，但是需要根据ROC确认最佳阈值！
