### ISSUE TITLE
请问作者预训练模型用的什么数据集？

### ISSUE THREAD

**Issue by jiamingzhang94** [sirius-ai/MobileFaceNet_TF#60]
另外在比较新的移动端CPU测试过速度没？
感谢！

**Comment by weidongmei123** [comment]
> 另外在比较新的移动端CPU测试过速度没？
> 感谢！

请问您测试过了吗？

**Comment by powerGet123** [comment]
移动端没测试过，只在linux下测试过，准确率很高，延时也低

**Comment by guker** [comment]
> 移动端没测试过，只在linux下测试过，准确率很高，延时也低

你是使用的什么数据集测试的
