### ISSUE TITLE
 Cannot feed value of shape (112, 112, 3) for Tensor 'input:0', which has shape '(?, 112, 112, 3)'

### ISSUE THREAD

**Issue by JionBin** [sirius-ai/MobileFaceNet_TF#69]
When I train the model by "python3 train_nets.py --class_number=85742", I got the errors:
`File "train_nets.py", line 235, in <module>
    feed_dict=feed_dict)
ValueError: Cannot feed value of shape (112, 112, 3) for Tensor 'input:0', which has shape '(?, 112, 112, 3)'
`
Is any one encounter the same error? Any suggestions? Thanks.

My env:
tensorflow             1.5.0
tensorflow-estimator   2.2.0
tensorflow-tensorboard 1.5.1
opencv-python          3.4.10.35
python                 3.5
scipy                  1.4.1
sklearn                0.0
mxnet                  1.6.0
numpy                  1.16.4
pickle5                0.0.11

**Comment by LeiiY** [comment]
@JionBin  hello， i meet the same problem like u，i wonder how u solved it，many thx。
Tensor("img_inputs:0", shape=(?, 112, 112, 3), dtype=float32)
![image](https://user-images.githubusercontent.com/28568741/141255015-57d1039c-03bf-4bc7-8113-fb87ec7349cd.png)
