### ISSUE TITLE
questions about the inference loss

### ISSUE THREAD

**Issue by zfs1993** [sirius-ai/MobileFaceNet_TF#9]
i check the inference loss on tensorboard and find that it increase sharply after every epoch. can you tell me the reason. i think it only occur when the data doesn't shuffle fully。

**Comment by SOLARleisu** [comment]
I have the same problem

**Comment by zfs1993** [comment]
> I have the same problem

you can see the reason in closed issue

**Comment by zfs1993** [comment]
you can see the reason in closed issue

**Comment by SOLARleisu** [comment]
thanks
